<?php

use MappDigital\Cloud\Block\TIDatalayer;

/**
 * @author Mapp Digital
 * @copyright Copyright (c) 2025 Mapp Digital US, LLC (https://www.mapp.com)
 * @package MappDigital_Cloud
 * @var $block TIDatalayer
 */

// SecureHtmlRenderer is available since version 2.4
if (class_exists('Magento\Framework\View\Helper\SecureHtmlRenderer')):
    /**
     * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
     */
    ?>
    <?= /* noEscape */ $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    'window._ti=' . $this->getDataLayer() . ';',
    false);
    ?>
<?php else: ?>
    <script type="text/javascript">window._ti = <?= $escaper->escapeHtml($block->getDataLayer()) ?>;</script>
<?php endif ?>
<?= /* noEscape */ $block->getScript(); ?>
