<?php
/**
 * @author Mapp Digital
 * @copyright Copyright (c) 2021 Mapp Digital US, LLC (https://www.mapp.com)
 * @package MappDigital_Cloud
 */

use MappDigital\Cloud\Block\TIDatalayer;

// SecureHtmlRenderer is available since version 2.4
if (class_exists('Magento\Framework\View\Helper\SecureHtmlRenderer')) {
    /**
     * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
     * @var TIDatalayer $this
     */
    echo $secureRenderer->renderTag(
        'script',
        ['type' => 'text/javascript'],
        'window._ti=' . $this->getDataLayer() . ';' . $this->getScript(),
        false);
} else {
    echo '<script type="text/javascript">' .  'window._ti=' . $this->getDataLayer() .';' . $this->getScript() . '</script>';
}
