<?php
/**
 * @author Mapp Digital
 * @copyright Copyright (c) 2023 Mapp Digital US, LLC (https://www.mapp.com)
 * @package MappDigital_Cloud
 */

use MappDigital\Cloud\Block\Webpush\Initialise;

/** @var $block Initialise */
if ($block->canInitJsFiles() && $alias = $block->getAlias()): ?>
    <?php foreach ($block->getPageAssets() as $url): ?>
        <script type="text/javascript" async defer src="<?= $escaper->escapeHtml($url) ?>"> </script>' . PHP_EOL;
    <?php endforeach ?>

    <script><?= $escaper->escapeHtml($block->getUserConfirmJs()) ?></script>
<?php endif ?>
