<?php
/**
 * @author Mapp Digital
 * @copyright Copyright (c) 2022 Mapp Digital US, LLC (https://www.mapp.com)
 * @package MappDigital_Cloud
 */
namespace MappDigital\Cloud\Console\Command;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\App\State;
use Magento\Newsletter\Model\Subscriber;
use Magento\Newsletter\Model\SubscriberFactory;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

class SubscribeCustomerTestTool extends AbstractCommand
{
    const COMMAND_NAME = "mapp:newsletter:subscription";

    private SubscriberFactory $subscriberFactory;

    public function __construct(
        ResourceConnection $resource,
        State $state,
        SubscriberFactory $subscriberFactory,
        $name = null
    ){
        parent::__construct($resource, $state, $name);
        $this->subscriberFactory = $subscriberFactory;
    }

    protected function configure()
    {
        $this->addArgument(
            'customer_id',
            InputArgument::REQUIRED,
            'Customer ID to Subscribe or Unsubscribe'
        );

        $this->addOption(
            'unsubscribe',
            InputOption::VALUE_NONE
        );

        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Access (Un)Subscribe by customer ID functions via console command due to them being deprecated within Magento Propper
     *
     * @return void
     */
    public function doExecute()
    {
        $this->getOutput()->writeln('<info>Updating Customer Subscription...</info>');
        if (!$this->getInput()->getOption('unsubscribe')) {
            $this->subscriberFactory->create()->subscribeCustomerById(
                $this->getInput()->getArgument('customer_id')
            );
            return;
        }

        $this->subscriberFactory->create()->unsubscribeCustomerById(
            $this->getInput()->getArgument('customer_id')
        );

        $this->getOutput()->writeln('<info>Customer Subscription Updated</info>');
    }
}
