version: '3'
services:
    web:
        image: ${PHPIMAGE}
        container_name: local.domain.com
        user: application
        environment:
          - MAGENTO_VERSION=${MAGENTO_VERSION}
          - WEB_ALIAS_DOMAIN=local.domain.com
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=4048M
          - PHP_MAX_EXECUTION_TIME=3000
          - PHP_POST_MAX_SIZE=900M
          - PHP_UPLOAD_MAX_FILESIZE=2024M
          - COMPOSER_VERSION=1
          - XDEBUG_REMOTE_AUTOSTART=1
          - XDEBUG_REMOTE_CONNECT_BACK=1
          ## IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
          ## docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' local.domain.com
          ##- XDEBUG_REMOTE_HOST=172.27.0.7
          ##- XDEBUG_REMOTE_PORT=9000
        volumes:
          - ./runner.sh:/runner.sh
          - ./wait-for-it.sh:/wait-for-it.sh
          - ./db.php:/db.php
          - ./app:/app:cached
          - "./../../src:/plugincode"
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        links:
          - mysql
        networks:
          - mapp
    mysql:
        image: mariadb:10.4
        container_name: mysql
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
        networks:
          - mapp
    e2e-electron:
        container_name: cypress
        entrypoint: ["/bin/bash", "./cypress_entrypoint.sh"]
        image: "cypress/included:4.1.0"
        volumes:
          - ./../cypress:/cypress
          - ./../cypress.json:/cypress.json
          - ./../cypress_entrypoint.sh:/cypress_entrypoint.sh
          - ./../cypress_run.sh:/cypress_run.sh
          - ./../results:/results
          - ./wait-for-it.sh:/wait-for-it.sh
        networks:
          - mapp
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - mapp
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data02:/usr/share/elasticsearch/data
        networks:
            - mapp
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data03:/usr/share/elasticsearch/data
        networks:
            - mapp
volumes:
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local
    db-data:
        external: false
networks:
    mapp:

